### ISSUE TITLE
Keep searchtext highlight case

### ISSUE THREAD

**Issue by FireLemons** [FireLemons/Abbreviation-Autocomplete#17]
the highlighted substring of the search text currently matches the case of the search text.
![image](https://user-images.githubusercontent.com/8918762/95639690-1119b380-0a5f-11eb-973b-ade72df8ae38.png)
See how the `and`s are all capitalized? I'd like it so that the case of the original strings is preserved. So `ANDorra` would be `Andorra` and `RwANDa` would be `Rwanda`

[this repo](https://github.com/FireLemons/Abbreviation-Autocomplete) is a live example of the autocomplete and is much easier to work with. It's a static webpage. It's hosted here https://firelemons.github.io/AutocompleteExample/

**Comment by rohanj-02** [comment]
Hey! I would like to work on this issue.
