### ISSUE TITLE
Add function to check whether the text in the input field is an element of data

### ISSUE THREAD

**Issue by FireLemons** [FireLemons/Abbreviation-Autocomplete#21]
for example consider this object passed to abbreviation-autocomplete's `data` prop

    [
     {
        a: "ATL",
        d: "Hartsfield–Jackson Atlanta International Airport"
      },
      {
        a: "LAX",
        d: "Los Angeles International Airport"
      }
    ]
`ATL` and `LAX` are elements of data  
  
I'd also like the function to take a boolean parameter that determines if case sensitivity matters  
  
[this repo](https://github.com/FireLemons/Abbreviation-Autocomplete) is a live example of the autocomplete and is much easier to work with. It's a static webpage. It's hosted here https://firelemons.github.io/AutocompleteExample/

**Comment by adhammo** [comment]
Hello @FireLemons,

If I understand correctly, you want a function which takes an abbreviation and checks if that abbreviation exists in the data prop and optionally a bool that makes checking case sensitive and defaults to false, right?

If so what would you like the name of the function.

**Comment by FireLemons** [comment]
@adhammo a function which takes the text currently in the `<input type="text">` and checks if it's an abbreviation from `data`. and that input is bound to the `searchText` prop.  
  
I think it would be better for the case sensitivity to default to being sensitive.  
  
I'd probably name it `isOption`

**Comment by FireLemons** [comment]
@adhammo would you like this assigned?

**Comment by adhammo** [comment]
yeah sure. assign it to me
