### ISSUE TITLE
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders.

### ISSUE THREAD

**Issue by NeelavBarai** [FireLemons/Abbreviation-Autocomplete#27]
Hi Developer,
First of all, thank you for the effort. 

I am using the exact code as shown in the example and I am getting the below error. Can you suggest a solution for it?

> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "searchText"
found in
<AbbreviationAutocomplete
       <Root

**Comment by FireLemons** [comment]
It looks like I need a local copy of all the props in the component
https://stackoverflow.com/a/39910248
I'll get on it soon

**Comment by FireLemons** [comment]
note for myself: also update debounce, min.js

**Comment by FireLemons** [comment]
@NeelavBarai ok it's fixed. use the new `@update:search-text` to listen for changes to the component's searchText. The example is updated.
